### ISSUE TITLE
Current code/integration is depricated?

### ISSUE THREAD

**Issue by doctornkz** [signalfx/signalfx-java#100]
Good day! I've got the letter from SignalFX support:
```
As SFx Java agent is deprecated please find the below link to our Splunk Otel Java instrumentation.
https://github.com/signalfx/splunk-otel-java

That is the documentation you are looking for.
```
I suppose we can add disclaimer to avoid misunderstanding from SFX community. I reached this `signalfx-java` project yesterday via google and waste the time to build a half-workable code. And after I fount Opentelemetry approach. WDYT?

**Comment by mpetazzoni** [comment]
@doctornkz This repository is for a Java client library for reporting metrics and streaming metrics with Signalflow. The "SignalFx Java Agent" that is being deprecated is from github.com/signalfx/signalfx-java-tracing, a different repository.

If you're trying to instrument your application with distributed tracing, please use the OpenTelemetry Java Agent going forward. For metrics, or metrics streaming needs, you can still use this client library.
