### ISSUE TITLE
Support for MultiToken clients

### ISSUE THREAD

**Issue by irisgve** [signalfx/signalfx-java#232]
Are there any plans of supporting multi-token client initialisation similar to https://github.com/signalfx/golib/blob/master/sfxclient/multitokensink.go?

**Comment by mtwo** [comment]
Hey there! We definitely recommend taking a look at our OpenTelemetry-Java artifact, as our work has been focused there for over two years.

That being said, I don't think that it supports using multiple tokens simultaneously either. Can you tell us more about your used case?

**Comment by irisgve** [comment]
We are using a pipeline to deliver the metrics for a lot of services to sfx and ideally some big producer of metrics would be behind an ingest token so if it starts going over MTS limits then the blast radius for throttling is reserved on that service. This is handled currently within the sfx go client library as above but sfx java library does not.

**Comment by breedx-splk** [comment]
Hi @irisgve. We are in the process of deprecating this repository and are encouraging users to migrate to OpenTelemetry. As part of this process, we are cleaning up stale issues like this one.

Please feel free to reopen if you wish to continue this discussion, but please be aware that we are limiting changes to security patches only at this point. Thank you for your understanding.
