### ISSUE TITLE
Bump to slf4j major version with patch version of lib itself?

### ISSUE THREAD

**Issue by zeldigas** [signalfx/signalfx-java#288]
Hi, I see that 1.0.25 was bumped to slf4j 2.x version. While api is backward compatible from code perspective, it is still very questionable decision.

I'd like to propose you to consider roll this back or update your versioning at least in minor part.

**Comment by mateuszrzeszutek** [comment]
Hey @zeldigas ,
`sfl4j-api` is a compile dependency in this project, and we're not using any of the newer APIs. Are you able to exclude it in your build config?

**Comment by zeldigas** [comment]
@mateuszrzeszutek  I can but without this there is a chance that it will conflict with other transitive dependency and win. This leads to no logs at all. I understand that this can be done by pinning version, but still this is something that is not good.

Example:

Create simple project with deps:
```xml
        <dependency>
            <groupId>com.signalfx.public</groupId>
            <artifactId>signalfx-java</artifactId>
            <version>1.0.27</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.11</version>
        </dependency>
```
And this simple code 
```java
    private static Logger log = LoggerFactory.getLogger(Tesrig.class);

    public static void main(String[] args) {
        log.warn("This is not working configuration");
    }
```

During execution, you get the following error message
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/dpavlov/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

That is my point - it becomes fragile and while I understand that this can be solved with exclusion of dependency or simply explicitly setting version of slf4j api this is still don't excuse bump of patch version in signalfx-java

**Comment by breedx-splk** [comment]
@zeldigas This issue is quite stale, so I'm going to close it in hopes that this is no longer a concern. We are in the process of deprecating this library and ending support next year. 

You mentioned updating the minor version, which implies semantic versioning. This legacy repository never adopted semantic versioning.
