### ISSUE TITLE
Handle expired-tsid stream message

### ISSUE THREAD

**Issue by mpetazzoni** [signalfx/signalfx-java#33]
https://developers.signalfx.com/docs/stream-messages-specification#expired-tsid-messages

See https://github.com/signalfx/signalfx-python/commit/5782c9d8d51d2c01685200b0e25e0e11624d7bca for equivalent Python implementation.

**Comment by dgriff-tools** [comment]
here is PR for this change

see https://github.com/signalfx/signalfx-java/pull/34

**Comment by dgriff-tools** [comment]
closing as enhancement merged
