### ISSUE TITLE
Unshaded Dependency Classes in Jar

### ISSUE THREAD

**Issue by jrduncans** [signalfx/signalfx-java#57]
Starting with version 0.0.40, unshaded dependency classes are showing up in the JAR. In particular, we hit problems due to SLF4J, but here's all the paths I see not under com/signalfx:

org/slf4j
google/protobuf/
com/github/os72/protobuf351

**Comment by mpetazzoni** [comment]
@jrduncans,

Thanks for reporting this.

The `google/protobuf` path only contains base ProtoBuf definitions that need to be at this path for the protobuf library to work. Since there are no classes under this path, you should be fine. For `com/github/os72/protobuf351`, that's a shaded version of the protobuf library (from https://github.com/os72/protobuf-java-shaded-351), and it uses a package path that encodes the library version (`protobuf351`) so it doesn't cause any conflicts.

As for SLF4J, it _think_ it should have been shaded. I need to look into that. It looks like it's only `slf4j-api` so that shouldn't cause too much trouble, but it probably should be shaded as well.

**Comment by tlisonbee** [comment]
Would it make more sense to have the transitive dependency on `slf4j-api`?

Including it unshaded is obviously a problem.  But rewriting the package seems a bit odd to for that particular dependency.

Also, I know it is kind of minor but it is a bit of a blocking issue for us that would be nice to get resolved as quickly as possible.  Any ETA?

**Comment by ezoerner** [comment]
It does cause trouble because the version of `slf4j-api` is not the same as what the application is using, so when attempting to `set assemble` a deployment jar there is a merge failure.

**Comment by mpetazzoni** [comment]
Looking at it now. Will get back to you shortly.

**Comment by mpetazzoni** [comment]
@jrduncans, @tlisonbee, @ezoerner, I've just released 0.0.44 which shades SLF4J as well.

**Comment by tlisonbee** [comment]
Great, thanks!  Will check it out now.

**Comment by ezoerner** [comment]
This issue should be reopened. By shading SLF4J, you changed the public API due to `Slf4jReporter#outputTo(Logger)`

**Comment by tlisonbee** [comment]
`slf4j-api` shouldn't be shaded or included in the jar.  It should be a transitive dependency.

**Comment by mpetazzoni** [comment]
I'm not sure what you mean by "it should be a transitive dependency". Our code in `signalfx-java` depends on SLF4J, so it has to be declared as a compile-scope dependency in our POM.

**Comment by jrduncans** [comment]
Yes, it should be a compile-scope dependency, and users of the library should get that as a transitive dependency. It should NOT be included in your published JAR.

**Comment by tlisonbee** [comment]
I can see how my comment might have been confusing.

What I meant was "`slf4j-api` should appear as a transitive dependency to users of your library" vs. baked into your jar.

**Comment by mpetazzoni** [comment]
@tlisonbee `io.dropwizard.metrics` includes SLF4J as a `compile`-scope dependency:

```
[INFO] +- io.dropwizard.metrics:metrics-core:jar:3.2.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.5:compile
```

Do you want me to make an explicit exclusion for this? Otherwise the `signalfx-codahale` JAR will still contain SLF4J.

**Comment by jrduncans** [comment]
In case you need it, it looks like https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html covers how to include/exclude specific artifacts.

**Comment by mpetazzoni** [comment]
Ok, release 0.0.45 coming up shortly.

**Comment by jrduncans** [comment]
Not being experienced with the shade plugin, I'm not sure if using inclusions will automatically change it to opt-in only mode, but I would either:

1) Include only specific jars to shade in your maven-shade-plugin config
2) If that doesn't work the way I'd hope, then at least exclude the slf4j-api from the maven-shade-plugin config

**Comment by mpetazzoni** [comment]
@jrduncans this is no longer a shading issue, but a dependency definition issue.

**Comment by tlisonbee** [comment]
What you want is to have `slf4j-api` to show up as a compile dependency in the pom,
http://central.maven.org/maven2/com/signalfx/public/signalfx-codahale/0.0.44/signalfx-codahale-0.0.44.pom

But not have it included in the jar.

That way, when we included it in our project, we'll see the transitive dependency on `slf4j-api` and it will be compatible with slf4j-api implementations that we provide.

**Comment by mpetazzoni** [comment]
@tlisonbee using a `compile` scope dependency is just the default, and that leads to the dependency being included in the final shaded JAR. I'm using a `provided` scope dependency instead, and it's then up to you to provide `slf4j-api` in your build.

**Comment by mpetazzoni** [comment]
@jrduncans excluding it from the final shaded JAR leads to exactly the same outcome though...

**Comment by ezoerner** [comment]
Is there a new revision of the library coming then?

**Comment by mpetazzoni** [comment]
I've just pushed a new `0.0.45-SNAPSHOT` artifact to the snapshots repo. Could you confirm it looks like what you expect?

**Comment by mpetazzoni** [comment]
@jrduncans @ezoerner Looking good? Should I release 0.0.45?

**Comment by tlisonbee** [comment]
Yes, it is ready for release.  Thanks.

**Comment by mpetazzoni** [comment]
Done

**Comment by tlisonbee** [comment]
Thanks @mpetazzoni  

We appreciate you jumping on this right away.
