### ISSUE TITLE
README.md example for adding dimensions with yammer 2.0 incorrect

### ISSUE THREAD

**Issue by eabbott** [signalfx/signalfx-java#6]
Adding Dimensions and SignalFx metadata to Codahale metrics -> Yammer Metrics 2.0.x
The example is copy-pasted from above, and does not reflect the Queue metric as shown in the 3.0 code.

**Comment by mdubbyap** [comment]
Thanks for noticing this!  We've fixed it up, let me know if there are any other issues!

**Comment by eabbott** [comment]
Thanks @mdubbyap, I'll let you know if anything else pops up as I kick the tires a bit.
