### ISSUE TITLE
Yammer Metrics Setup Example Compilation Errors & Typo in README.md

### ISSUE THREAD

**Issue by imedmar** [signalfx/signalfx-java#64]
In the `Set up Yammer metrics` section, the metric registry is set up as:
```
final MetricRegistry metricsRegistry = new MetricRegistry();
```
It should instead be the following (note `MetricRegistry` was changed to `MetricsRegistry`):
```
final MetricsRegistry metricsRegistry = new MetricsRegistry();
```

Also there's a typo in the `signalfxReporter` where it should be `metricsRegistry` instead of `metricsRegistery`.

**Comment by mpetazzoni** [comment]
@imedmar Thanks for reporting! Would you be able to provide a PR to address those issues?

**Comment by imedmar** [comment]
On it 😄

**Comment by imedmar** [comment]
Now I remember why I didn't move forward with a PR at first:
```
ERROR: Permission to signalfx/signalfx-java.git denied to imedmar.
```
FYI @mpetazzoni

**Comment by mpetazzoni** [comment]
@imedmar You need to create a fork, push your branch to your fork, and submit a PR from that branch. See https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project for more details.
