### ISSUE TITLE
signalfx-yammer-0.0.21 not found

### ISSUE THREAD

**Issue by eabbott** [signalfx/signalfx-java#7]
The README suggests yammer 2.0.x is supported through the signalfx-yammer jar file, but that file is not found at:
http://mvnrepository.com/artifact/com.signalfx.public

Nor is it built by

git clone git@github.com:signalfx/signalfx-java
cd signalfx-java
git checkout 0.0.21
mvn clean package

**Comment by mdubbyap** [comment]
signalfx-yammer will be available when we release 0.0.23

**Comment by eabbott** [comment]
Then I'd suggest the README.md is at best misleading.
