### ISSUE TITLE
SignalFxReporter doesn't maintain the state of metrics when we invoke report() method

### ISSUE THREAD

**Issue by ragidayananda** [signalfx/signalfx-java#80]
I am trying to log my application metrics to SignalFx using SignalFxReporter class. I'm initializing the metric registry and SignalFxReporter at the time of app start and set   SignalFxReporter to report every 1 minute.

```
final String signalfxAuthToken = configuration.getString("signalfx.authToken");
final SignalFxReporter signalfxReporter = new SignalFxReporter.Builder(
      METRIC_REGISTRY,
      new StaticAuthToken(signalfxAuthToken),
 ).addDimension("env", "prod").build();
metricMetadata = signalfxReporter.getMetricMetadata();

signalfxReporter.start(1, TimeUnit.MINUTES); 
```

I see that its reporting the same metrics repeatedly. I just gonethrough the signalfxReporter class impl and I don't see that its maintaining the state of the metrics when it reports. It just reports all the available metrics in MetricRegistry all the time. 

Is it expected behavior? I am actually looking for a non blocking way of SFxReporting from java application where it reports only new or changed metrics.

**Comment by jkwatson** [comment]
@ragidayananda this is the expected behavior, yes. All metrics should be reported every reporting interval, whether they have changed values or not.
