### ISSUE TITLE
Jackson dependency has security vulnerability, twistlock will not build without an update.

### ISSUE THREAD

**Issue by tschiman** [signalfx/signalfx-java#84]
In my release process we use Twistlock to scan for libraries with known vulnerabilities. Jackson 2.9.10 has vulnerabilities that were resolved in 2.9.10.1 and 2.9.10.2 see: [link](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9). Twistlock is forcing an upgrade to 2.9.10.2 to resolve these issues. Please update the library with the updated version of jackson so we can pass our security vulnerably scans. 

What we are experiencing is that excluding the jackson dependencies from the project is not sufficient to change the version. We think this is happening because of the shading used in the project for fasterxml.

Currently using version 0.2.1.

**Comment by jchengsfx** [comment]
Released in version 1.0.1.
