### ISSUE TITLE
Twist Lock Scan vulnerability with <jackson.databind.version>2.9.10.3</jackson.databind.version> 

### ISSUE THREAD

**Issue by sandy11apr** [signalfx/signalfx-java#88]
Please bump the version to **2.9.10.4** or the **latest Jackson databind verison**. It is blocking us. 
exclusion is not working. 
<jackson.databind.version>2.9.10.3</jackson.databind.version>

From: Finicity

**Comment by tschiman** [comment]
After chatting with the developers on jackson, they say that moving to 2.10.x would resolve a lot of issues with security, any chance that could be upgraded?

**Comment by dloucasfx** [comment]
Fixed in release https://github.com/signalfx/signalfx-java/releases/tag/1.0.3
PR: https://github.com/signalfx/signalfx-java/pull/89
