### ISSUE TITLE
Twistlock vulnerability for io.netty_netty-codec

### ISSUE THREAD

**Issue by sandy11apr** [signalfx/signalfx-java#90]
Please bump up the latest version for  **io.netty_netty-codec** it is flagged as high Twistlock vulnerability. 

Thanks, Sandeep From Finicity

**Comment by jchengsfx** [comment]
@sandy11apr I am not seeing a direct dependency for `io.netty:netty-codec` in this repo.  Please confirm or provide more details.  Thanks!

**Comment by jchengsfx** [comment]
@sandy11apr Closing this issue for now. Please open a new issue when you can confirm the vulnerable dependency or are able to provide more details.  Thanks!
