### ISSUE TITLE
Flow client can't be reused after connection lost.

### ISSUE THREAD

**Issue by zeldigas** [signalfx/signalfx-java#94]
I use flow client (lib version 1.0.3) to subscribe on metrics using code pretty close to one described in readme:
```kotlin
while (true) {
    val computation = flow.execute(STATUS_QUERY)
    try {
        for (message in computation) {
            handleRecievedMessage(message)
        }
    } catch (ex: SignalFlowException) {
        logger.error(ex) { "Flow subscription stopped, will resubscribe after timeout $DELAY_BETWEEN_FLOW_SUBSCRIPTIONS" }
        delay(DELAY_BETWEEN_FLOW_SUBSCRIPTIONS.toMillis())
    }
}
```
Here `flow` is a client that created once. 

Turned out that if exception occurs during polling, (usually it looks like `c.s.s.WebSocketTransport$TransportConnection - Lost WebSocket connection with stream.signalfx.com/[ipadress-here]:443 (1006).`) I can't repeat query on first line of cycle.

Instead of correct result I got NPE:
```
Caused by: java.lang.NullPointerException
at com.signalfx.signalflow.WebSocketTransport$TransportConnection.sendMessage(WebSocketTransport.java:535)
```

I'm not sure if it's a bug or not. If not, please improve readme by specifying that on lost connection, client should be recreated or restarted somehow.

**Comment by mpetazzoni** [comment]
That is definitely a bug. I'll try to work on a fix; thanks for reporting.

**Comment by zeldigas** [comment]
@mpetazzoni  do you have any news on this?

**Comment by breedx-splk** [comment]
Hi @zeldigas . As mentioned elsewhere, this repository is being deprecated and will be archived next year. As part of that effort, we are closing out stale issues like this one. Please feel free to open again if this becomes a consideration again.

The signalflow clients are expected to remain supported, but will move out of this repository and change ownership.

Thanks for your understanding.
